<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ivp.ai.api\ivp.ai.api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="testdata\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
